services:
  ebil:
    build:
      context: .
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app


