services:
  ebil:
    build:
      context: .
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    restart: always
    hostname: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
