"""add new tables

Revision ID: 528e661fa0db
Revises: 428977cf423e
Create Date: 2024-02-29 16:07:25.135139

"""
from typing import Sequence, Union

import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '528e661fa0db'
down_revision: Union[str, None] = '428977cf423e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('bills',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('total', sa.Float(), nullable=False),
                    sa.Column('rest', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('payment', sa.JSON(), nullable=True),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('bills_products',
                    sa.Column('bill_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('bill_id', 'product_id')
                    )

    op.alter_column('users', 'id',
                    existing_type=sa.BIGINT(),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    autoincrement=True)

    op.drop_index('ix_user_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_user_email', 'users', ['email'], unique=True)

    op.alter_column('users', 'id',
                    existing_type=sa.Integer(),
                    type_=sa.BIGINT(),
                    existing_nullable=False,
                    autoincrement=True)

    op.drop_table('bills_products')
    op.drop_table('bills')
    op.drop_table('products')
    # ### end Alembic commands ###
